// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: Shapes.proto

package Shapes

import (
	Representations "github.com/maltegrosse/adapt-go/Representations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShapeType_ShapeTypeEnum int32

const (
	ShapeType_LinearRing      ShapeType_ShapeTypeEnum = 0
	ShapeType_LineString      ShapeType_ShapeTypeEnum = 1
	ShapeType_MultiLineString ShapeType_ShapeTypeEnum = 2
	ShapeType_MultiPoint      ShapeType_ShapeTypeEnum = 3
	ShapeType_MultiPolygon    ShapeType_ShapeTypeEnum = 4
	ShapeType_Point           ShapeType_ShapeTypeEnum = 5
	ShapeType_Polygon         ShapeType_ShapeTypeEnum = 6
	ShapeType_RasterGrid      ShapeType_ShapeTypeEnum = 7
)

// Enum value maps for ShapeType_ShapeTypeEnum.
var (
	ShapeType_ShapeTypeEnum_name = map[int32]string{
		0: "LinearRing",
		1: "LineString",
		2: "MultiLineString",
		3: "MultiPoint",
		4: "MultiPolygon",
		5: "Point",
		6: "Polygon",
		7: "RasterGrid",
	}
	ShapeType_ShapeTypeEnum_value = map[string]int32{
		"LinearRing":      0,
		"LineString":      1,
		"MultiLineString": 2,
		"MultiPoint":      3,
		"MultiPolygon":    4,
		"Point":           5,
		"Polygon":         6,
		"RasterGrid":      7,
	}
)

func (x ShapeType_ShapeTypeEnum) Enum() *ShapeType_ShapeTypeEnum {
	p := new(ShapeType_ShapeTypeEnum)
	*p = x
	return p
}

func (x ShapeType_ShapeTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShapeType_ShapeTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_Shapes_proto_enumTypes[0].Descriptor()
}

func (ShapeType_ShapeTypeEnum) Type() protoreflect.EnumType {
	return &file_Shapes_proto_enumTypes[0]
}

func (x ShapeType_ShapeTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShapeType_ShapeTypeEnum.Descriptor instead.
func (ShapeType_ShapeTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{9, 0}
}

type BoundingBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinY *Representations.NumericRepresentationValue `protobuf:"bytes,1,opt,name=MinY,proto3" json:"MinY,omitempty"`
	MinX *Representations.NumericRepresentationValue `protobuf:"bytes,2,opt,name=MinX,proto3" json:"MinX,omitempty"`
	MaxY *Representations.NumericRepresentationValue `protobuf:"bytes,3,opt,name=MaxY,proto3" json:"MaxY,omitempty"`
	MaxX *Representations.NumericRepresentationValue `protobuf:"bytes,4,opt,name=MaxX,proto3" json:"MaxX,omitempty"`
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetMinY() *Representations.NumericRepresentationValue {
	if x != nil {
		return x.MinY
	}
	return nil
}

func (x *BoundingBox) GetMinX() *Representations.NumericRepresentationValue {
	if x != nil {
		return x.MinX
	}
	return nil
}

func (x *BoundingBox) GetMaxY() *Representations.NumericRepresentationValue {
	if x != nil {
		return x.MaxY
	}
	return nil
}

func (x *BoundingBox) GetMaxX() *Representations.NumericRepresentationValue {
	if x != nil {
		return x.MaxX
	}
	return nil
}

type LineString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*Shape `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
}

func (x *LineString) Reset() {
	*x = LineString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineString) ProtoMessage() {}

func (x *LineString) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineString.ProtoReflect.Descriptor instead.
func (*LineString) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{1}
}

func (x *LineString) GetPoints() []*Shape {
	if x != nil {
		return x.Points
	}
	return nil
}

type LinearRing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*Shape `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
}

func (x *LinearRing) Reset() {
	*x = LinearRing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinearRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearRing) ProtoMessage() {}

func (x *LinearRing) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearRing.ProtoReflect.Descriptor instead.
func (*LinearRing) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{2}
}

func (x *LinearRing) GetPoints() []*Shape {
	if x != nil {
		return x.Points
	}
	return nil
}

type MultiLineString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineStrings []*Shape `protobuf:"bytes,1,rep,name=LineStrings,proto3" json:"LineStrings,omitempty"`
}

func (x *MultiLineString) Reset() {
	*x = MultiLineString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiLineString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiLineString) ProtoMessage() {}

func (x *MultiLineString) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiLineString.ProtoReflect.Descriptor instead.
func (*MultiLineString) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{3}
}

func (x *MultiLineString) GetLineStrings() []*Shape {
	if x != nil {
		return x.LineStrings
	}
	return nil
}

type MultiPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*Shape `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
}

func (x *MultiPoint) Reset() {
	*x = MultiPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPoint) ProtoMessage() {}

func (x *MultiPoint) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPoint.ProtoReflect.Descriptor instead.
func (*MultiPoint) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{4}
}

func (x *MultiPoint) GetPoints() []*Shape {
	if x != nil {
		return x.Points
	}
	return nil
}

type MultiPolygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Polygons []*Shape `protobuf:"bytes,1,rep,name=Polygons,proto3" json:"Polygons,omitempty"`
}

func (x *MultiPolygon) Reset() {
	*x = MultiPolygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPolygon) ProtoMessage() {}

func (x *MultiPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPolygon.ProtoReflect.Descriptor instead.
func (*MultiPolygon) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{5}
}

func (x *MultiPolygon) GetPolygons() []*Shape {
	if x != nil {
		return x.Polygons
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{6}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Polygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExteriorRing  *LinearRing   `protobuf:"bytes,1,opt,name=ExteriorRing,proto3" json:"ExteriorRing,omitempty"`
	InteriorRings []*LinearRing `protobuf:"bytes,2,rep,name=InteriorRings,proto3" json:"InteriorRings,omitempty"`
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{7}
}

func (x *Polygon) GetExteriorRing() *LinearRing {
	if x != nil {
		return x.ExteriorRing
	}
	return nil
}

func (x *Polygon) GetInteriorRings() []*LinearRing {
	if x != nil {
		return x.InteriorRings
	}
	return nil
}

type Shape struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64      `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type *ShapeType `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	// Types that are assignable to Subtype:
	//
	//	*Shape_LinearRing
	//	*Shape_LineString
	//	*Shape_MultiLineString
	//	*Shape_MultiPoint
	//	*Shape_MultiPolygon
	//	*Shape_Point
	//	*Shape_Polygon
	Subtype isShape_Subtype `protobuf_oneof:"subtype"`
}

func (x *Shape) Reset() {
	*x = Shape{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shape) ProtoMessage() {}

func (x *Shape) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shape.ProtoReflect.Descriptor instead.
func (*Shape) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{8}
}

func (x *Shape) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shape) GetType() *ShapeType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (m *Shape) GetSubtype() isShape_Subtype {
	if m != nil {
		return m.Subtype
	}
	return nil
}

func (x *Shape) GetLinearRing() *LinearRing {
	if x, ok := x.GetSubtype().(*Shape_LinearRing); ok {
		return x.LinearRing
	}
	return nil
}

func (x *Shape) GetLineString() *LineString {
	if x, ok := x.GetSubtype().(*Shape_LineString); ok {
		return x.LineString
	}
	return nil
}

func (x *Shape) GetMultiLineString() *MultiLineString {
	if x, ok := x.GetSubtype().(*Shape_MultiLineString); ok {
		return x.MultiLineString
	}
	return nil
}

func (x *Shape) GetMultiPoint() *MultiPoint {
	if x, ok := x.GetSubtype().(*Shape_MultiPoint); ok {
		return x.MultiPoint
	}
	return nil
}

func (x *Shape) GetMultiPolygon() *MultiPolygon {
	if x, ok := x.GetSubtype().(*Shape_MultiPolygon); ok {
		return x.MultiPolygon
	}
	return nil
}

func (x *Shape) GetPoint() *Point {
	if x, ok := x.GetSubtype().(*Shape_Point); ok {
		return x.Point
	}
	return nil
}

func (x *Shape) GetPolygon() *Polygon {
	if x, ok := x.GetSubtype().(*Shape_Polygon); ok {
		return x.Polygon
	}
	return nil
}

type isShape_Subtype interface {
	isShape_Subtype()
}

type Shape_LinearRing struct {
	LinearRing *LinearRing `protobuf:"bytes,101,opt,name=LinearRing,proto3,oneof"`
}

type Shape_LineString struct {
	LineString *LineString `protobuf:"bytes,102,opt,name=LineString,proto3,oneof"`
}

type Shape_MultiLineString struct {
	MultiLineString *MultiLineString `protobuf:"bytes,103,opt,name=MultiLineString,proto3,oneof"`
}

type Shape_MultiPoint struct {
	MultiPoint *MultiPoint `protobuf:"bytes,104,opt,name=MultiPoint,proto3,oneof"`
}

type Shape_MultiPolygon struct {
	MultiPolygon *MultiPolygon `protobuf:"bytes,105,opt,name=MultiPolygon,proto3,oneof"`
}

type Shape_Point struct {
	Point *Point `protobuf:"bytes,106,opt,name=Point,proto3,oneof"`
}

type Shape_Polygon struct {
	Polygon *Polygon `protobuf:"bytes,107,opt,name=Polygon,proto3,oneof"`
}

func (*Shape_LinearRing) isShape_Subtype() {}

func (*Shape_LineString) isShape_Subtype() {}

func (*Shape_MultiLineString) isShape_Subtype() {}

func (*Shape_MultiPoint) isShape_Subtype() {}

func (*Shape_MultiPolygon) isShape_Subtype() {}

func (*Shape_Point) isShape_Subtype() {}

func (*Shape_Polygon) isShape_Subtype() {}

type ShapeType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShapeType) Reset() {
	*x = ShapeType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shapes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeType) ProtoMessage() {}

func (x *ShapeType) ProtoReflect() protoreflect.Message {
	mi := &file_Shapes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeType.ProtoReflect.Descriptor instead.
func (*ShapeType) Descriptor() ([]byte, []int) {
	return file_Shapes_proto_rawDescGZIP(), []int{9}
}

var File_Shapes_proto protoreflect.FileDescriptor

var file_Shapes_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x1a, 0x15, 0x52, 0x65,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x02, 0x0a, 0x0b, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x42, 0x6f, 0x78, 0x12, 0x45, 0x0a, 0x04, 0x4d, 0x69, 0x6e, 0x59, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69,
	0x63, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x4d, 0x69, 0x6e, 0x59, 0x12, 0x45, 0x0a, 0x04, 0x4d, 0x69,
	0x6e, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54,
	0x2e, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x4d, 0x69, 0x6e,
	0x58, 0x12, 0x45, 0x0a, 0x04, 0x4d, 0x61, 0x78, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52,
	0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x04, 0x4d, 0x61, 0x78, 0x59, 0x12, 0x45, 0x0a, 0x04, 0x4d, 0x61, 0x78, 0x58,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x52,
	0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4e,
	0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x4d, 0x61, 0x78, 0x58, 0x22,
	0x39, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a,
	0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61,
	0x70, 0x65, 0x52, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x0a, 0x4c, 0x69,
	0x6e, 0x65, 0x61, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x06, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54,
	0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x06, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x48, 0x0a, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x69,
	0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x35, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x65,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61,
	0x70, 0x65, 0x52, 0x0b, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0x39, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2b, 0x0a,
	0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61,
	0x70, 0x65, 0x52, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x3f, 0x0a, 0x0c, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x08, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41,
	0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x70,
	0x65, 0x52, 0x08, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x73, 0x22, 0x31, 0x0a, 0x05, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x59,
	0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x5a, 0x22, 0x87,
	0x01, 0x0a, 0x07, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0c, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x69, 0x6f, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x69, 0x6f, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x12, 0x3e, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x69, 0x6f, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x4c,
	0x69, 0x6e, 0x65, 0x61, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x52, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x69, 0x6f, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xf0, 0x03, 0x0a, 0x05, 0x53, 0x68, 0x61,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e,
	0x53, 0x68, 0x61, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x3a, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x18, 0x65, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70,
	0x65, 0x73, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x0a, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x12, 0x3a, 0x0a, 0x0a, 0x4c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x4c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x0a, 0x4c, 0x69, 0x6e,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x49, 0x0a, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x67, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48,
	0x00, 0x52, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x3a, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x68, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53,
	0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x40,
	0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x18, 0x69,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61,
	0x70, 0x65, 0x73, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x12, 0x2b, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x31, 0x0a,
	0x07, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x41, 0x44, 0x41, 0x50, 0x54, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x42, 0x09, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x09,
	0x53, 0x68, 0x61, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0d, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x0a, 0x4c,
	0x69, 0x6e, 0x65, 0x61, 0x72, 0x52, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x10, 0x03,
	0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x10, 0x05, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x47, 0x72, 0x69, 0x64, 0x10, 0x07, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6c, 0x74, 0x65, 0x67, 0x72,
	0x6f, 0x73, 0x73, 0x65, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Shapes_proto_rawDescOnce sync.Once
	file_Shapes_proto_rawDescData = file_Shapes_proto_rawDesc
)

func file_Shapes_proto_rawDescGZIP() []byte {
	file_Shapes_proto_rawDescOnce.Do(func() {
		file_Shapes_proto_rawDescData = protoimpl.X.CompressGZIP(file_Shapes_proto_rawDescData)
	})
	return file_Shapes_proto_rawDescData
}

var file_Shapes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Shapes_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Shapes_proto_goTypes = []interface{}{
	(ShapeType_ShapeTypeEnum)(0), // 0: ADAPT.Shapes.ShapeType.ShapeTypeEnum
	(*BoundingBox)(nil),          // 1: ADAPT.Shapes.BoundingBox
	(*LineString)(nil),           // 2: ADAPT.Shapes.LineString
	(*LinearRing)(nil),           // 3: ADAPT.Shapes.LinearRing
	(*MultiLineString)(nil),      // 4: ADAPT.Shapes.MultiLineString
	(*MultiPoint)(nil),           // 5: ADAPT.Shapes.MultiPoint
	(*MultiPolygon)(nil),         // 6: ADAPT.Shapes.MultiPolygon
	(*Point)(nil),                // 7: ADAPT.Shapes.Point
	(*Polygon)(nil),              // 8: ADAPT.Shapes.Polygon
	(*Shape)(nil),                // 9: ADAPT.Shapes.Shape
	(*ShapeType)(nil),            // 10: ADAPT.Shapes.ShapeType
	(*Representations.NumericRepresentationValue)(nil), // 11: ADAPT.Representations.NumericRepresentationValue
}
var file_Shapes_proto_depIdxs = []int32{
	11, // 0: ADAPT.Shapes.BoundingBox.MinY:type_name -> ADAPT.Representations.NumericRepresentationValue
	11, // 1: ADAPT.Shapes.BoundingBox.MinX:type_name -> ADAPT.Representations.NumericRepresentationValue
	11, // 2: ADAPT.Shapes.BoundingBox.MaxY:type_name -> ADAPT.Representations.NumericRepresentationValue
	11, // 3: ADAPT.Shapes.BoundingBox.MaxX:type_name -> ADAPT.Representations.NumericRepresentationValue
	9,  // 4: ADAPT.Shapes.LineString.Points:type_name -> ADAPT.Shapes.Shape
	9,  // 5: ADAPT.Shapes.LinearRing.Points:type_name -> ADAPT.Shapes.Shape
	9,  // 6: ADAPT.Shapes.MultiLineString.LineStrings:type_name -> ADAPT.Shapes.Shape
	9,  // 7: ADAPT.Shapes.MultiPoint.Points:type_name -> ADAPT.Shapes.Shape
	9,  // 8: ADAPT.Shapes.MultiPolygon.Polygons:type_name -> ADAPT.Shapes.Shape
	3,  // 9: ADAPT.Shapes.Polygon.ExteriorRing:type_name -> ADAPT.Shapes.LinearRing
	3,  // 10: ADAPT.Shapes.Polygon.InteriorRings:type_name -> ADAPT.Shapes.LinearRing
	10, // 11: ADAPT.Shapes.Shape.Type:type_name -> ADAPT.Shapes.ShapeType
	3,  // 12: ADAPT.Shapes.Shape.LinearRing:type_name -> ADAPT.Shapes.LinearRing
	2,  // 13: ADAPT.Shapes.Shape.LineString:type_name -> ADAPT.Shapes.LineString
	4,  // 14: ADAPT.Shapes.Shape.MultiLineString:type_name -> ADAPT.Shapes.MultiLineString
	5,  // 15: ADAPT.Shapes.Shape.MultiPoint:type_name -> ADAPT.Shapes.MultiPoint
	6,  // 16: ADAPT.Shapes.Shape.MultiPolygon:type_name -> ADAPT.Shapes.MultiPolygon
	7,  // 17: ADAPT.Shapes.Shape.Point:type_name -> ADAPT.Shapes.Point
	8,  // 18: ADAPT.Shapes.Shape.Polygon:type_name -> ADAPT.Shapes.Polygon
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_Shapes_proto_init() }
func file_Shapes_proto_init() {
	if File_Shapes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Shapes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoundingBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinearRing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiLineString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiPolygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Polygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shape); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shapes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShapeType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Shapes_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Shape_LinearRing)(nil),
		(*Shape_LineString)(nil),
		(*Shape_MultiLineString)(nil),
		(*Shape_MultiPoint)(nil),
		(*Shape_MultiPolygon)(nil),
		(*Shape_Point)(nil),
		(*Shape_Polygon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Shapes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Shapes_proto_goTypes,
		DependencyIndexes: file_Shapes_proto_depIdxs,
		EnumInfos:         file_Shapes_proto_enumTypes,
		MessageInfos:      file_Shapes_proto_msgTypes,
	}.Build()
	File_Shapes_proto = out.File
	file_Shapes_proto_rawDesc = nil
	file_Shapes_proto_goTypes = nil
	file_Shapes_proto_depIdxs = nil
}
